#!/usr/bin/env bash
# Script to display listening ports with PID and program name

echo "Active Internet connections (only servers)"
ss -tuln -p

echo ""
echo "Active UNIX domain sockets (only servers)"
ss -xln -p
